"""
Django settings for taskflow project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------
# SECURITY / DEBUG
# ---------------------------

# Use env var in production, fallback for local dev
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")


DEBUG = False


ALLOWED_HOSTS = ["localhost", "127.0.0.1", 
                "taskflow-brendan-e86639abd341.herokuapp.com"]

CSRF_TRUSTED_ORIGINS = [
    "https://taskflow-brendan-e86639abd341.herokuapp.com",
]


# ---------------------------
# APPLICATIONS
# ---------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "todo",
]


# ---------------------------
# MIDDLEWARE
# ---------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # for static files on Heroku
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ---------------------------
# URL / TEMPLATES
# ---------------------------

ROOT_URLCONF = "taskflow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # top-level templates folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "taskflow.wsgi.application"


# ---------------------------
# DATABASE
# ---------------------------

# Use Postgres on Heroku, SQLite locally
if "DATABASE_URL" in os.environ:
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ---------------------------
# PASSWORD VALIDATION
# ---------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]


# ---------------------------
# INTERNATIONALIZATION
# ---------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ---------------------------
# STATIC FILES
# ---------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ---------------------------
# DEFAULTS
# ---------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------
# AUTH REDIRECTS
# ---------------------------

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "todo_list"
LOGOUT_REDIRECT_URL = "todo_list"
